import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#010101ff" },
  fullFlex: { flex: 1 },
  backButton: {
    margin: 15,
    backgroundColor: "#facc15",
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 20,
    alignSelf: "flex-start",
  },
  backText: { fontWeight: "700", color: "#1e293b", fontSize: 16 },
  title: { fontSize: 24, fontWeight: "700", textAlign: "center", color: "#e52020ff", marginBottom: 15 },
  flatListContent: { paddingVertical: 20, paddingBottom: 220 },
  textContainer: {
    backgroundColor: "#e4e2edff",
    padding: 12,
    marginVertical: 5,
    marginHorizontal: 15,
    borderRadius: 12,
    elevation: 2,
  },
  activeTextContainer: { backgroundColor: "#fef3c7", borderColor: "#facc15", borderWidth: 1 },
  text: { fontSize: 20, lineHeight: 30, textAlign: "center", color: "#1e293b" },
  activeText: { color: "#e11d48", fontWeight: "600" },
  bottomControls: { position: "absolute", bottom: 0, width: "100%", paddingHorizontal: 15, paddingBottom: 15 },
  playerCard: { borderRadius: 20, padding: 10, elevation: 5 },
  slider: { width: "100%", height: 30 },
  controls: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 6 },
  playButton: { justifyContent: "center", alignItems: "center" },
  timeText: { fontSize: 12, color: "#e5e7eb" },
  rateControls: { flexDirection: "row", justifyContent: "center", marginTop: 6 },
  rateButton: { backgroundColor: "#facc15", paddingHorizontal: 10, paddingVertical: 5, borderRadius: 8, marginHorizontal: 4 },
  activeRateButton: { backgroundColor: "#e11d48" },
  rateText: { fontSize: 14, fontWeight: "700", color: "#1e293b" },
  activeRateText: { color: "#fff" },
  bottomRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 8 },
  fontControls: { flexDirection: "row", alignItems: "center" },
  fontButton: { backgroundColor: "#facc15", paddingHorizontal: 10, paddingVertical: 5, borderRadius: 8, marginHorizontal: 5 },
  fontButtonText: { fontSize: 16, fontWeight: "700", color: "#1e293b" },
  fontSizeDisplay: { fontSize: 14, fontWeight: "600", color: "#b45309" },
  whatsappButton: { backgroundColor: "#25D366", padding: 8, borderRadius: 20, justifyContent: "center", alignItems: "center" },
});
